# Generated by Django 5.2.6 on 2026-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_audio_file_song_file_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
