# Generated by Django 5.2.6 on 2026-03-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
    ]
