# Generated by Django 5.2.6 on 2026-03-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_remove_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
